services:
  download-model:
    image: python:3.12-slim
    volumes:
      - ./weights:/weights
    command: >
      bash -c "pip install huggingface_hub &&
      hf download sodeeplearning/pozdgpt
      --include 'PozdGPT-awq-4bit/*'
      --local-dir /weights"

  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "${VLLM_PORT}:${VLLM_PORT}"
    volumes:
      - ./weights:/weights
    restart: unless-stopped
    environment:
      VLLM_USE_FLASHINFER_SAMPLER: "0"
    command:
      - --model
      - /weights/PozdGPT-awq-4bit
      - --served-model-name
      - pozdgpt
      - --quantization
      - compressed-tensors
      - --max-model-len
      - "8192"
      - --gpu-memory-utilization
      - "0.88"
      - --max-num-seqs
      - "6"
      - --kv-cache-dtype
      - fp8
      - --enable-prefix-caching
      - --api-key
      - $VLLM_API_KEY
      - --port
      - $VLLM_PORT
    depends_on:
      download-model:
        condition: service_completed_successfully

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - ./.redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - ./.pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  telegram:
    build:
      dockerfile: ./service_bot/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
