FROM nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./telegram/requirements.txt tele-reqs.txt
COPY ./requirements.txt pozd-reqs.txt

RUN pip3 install --no-cache-dir -r tele-reqs.txt
RUN pip3 install --no-cache-dir -r pozd-reqs.txt

RUN pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu121

COPY ./telegram ./telegram
COPY ./pozdnyakov ./telegram/pozdnyakov

CMD ["python3", "-u", "telegram/main.py"]
